### ISSUE TITLE
Error RunCommand::Response has no member named ‘standardoutput’

### ISSUE THREAD

**Issue by andreadelprete** [stack-of-tasks/dynamic_graph_bridge#27]
Hi,
when I try to compile dynamic_graph_bridge (branch hydro) I get the following error messages:

```
/home/adelpret/devel/sot_hydro/stacks/redundant_manipulator_control/dynamic_graph_bridge/src/ros_interpreter.cpp:33:52: error: ‘dynamic_graph_bridge_msgs::RunCommand::Response’ has no member named ‘standardoutput’
/home/adelpret/devel/sot_hydro/stacks/redundant_manipulator_control/dynamic_graph_bridge/src/ros_interpreter.cpp:33:72: error: ‘dynamic_graph_bridge_msgs::RunCommand::Response’ has no member named ‘standarderror’
```

Indeed by looking at the code it seems that `RunCommand::Response` has no member `standarderror` and `standardoutput`.  The line generating the error is:

```
interpreter_.python(req.input, res.result, res.standardoutput, res.standarderror);
```

and it was changed in [this commit](https://github.com/stack-of-tasks/dynamic_graph_bridge/commit/ebee4407bd8ddf432486d2ba7d225ad778a49b7a). If I revert it back to:

```
interpreter_.python(req.input, res.result, res.stdout, res.stderr);
```

I can compile without any problem. Maybe @olivier-stasse can help me with this?

**Comment by olivier-stasse** [comment]
Dear Andreas,
Thank you for your feedback.
Could you check if your dynamic_graph_bridge repository is using the hydro branch ?
Becase from the definition of the RunCommand.srv here:
https://github.com/stack-of-tasks/dynamic_graph_bridge_msgs/blob/hydro/srv/RunCommand.srv

It looks like it should res.standardoutput and res.standarderror.

Thanks in advance for your answer.

**Comment by andreadelprete** [comment]
Hi Olivier and thanks for your answer. I was indeed using the master branch of the repo dynamic_graph_bridge_msg. However, even after switching to the hydro branch, compiling it and installing it, the problem is still there.
Investigating a bit it seems that the problem is that rather than including the updated version of ```dynamic_graph_bridge_msgs/RunCommand.h``` in the install folder, I am including (in ```ros_interpreter.hh```) the version that is in ```~/devel/sot_hydro/stacks/redundant_manipulator_control/dynamic_graph_bridge_msgs/srv_gen/cpp/include```, which is not updated when I execute ```make install``` in dynamic_graph_bridge_msg. Of course I can easily fix this by copying the updated version in that folder, but I think I am missing something here.
Why isn't the second version of ```RunCommand.h``` updated when I run ```make install```?
And why is my code including that version rather than the one in my install folder?
