### ISSUE TITLE
Control signal called before definition

### ISSUE THREAD

**Issue by proyan** [stack-of-tasks/dynamic_graph_bridge#32]
In sot_loader.cpp: fillSensors(), angleControl_ is being called before being set. (call from sotLoader::oneIteration).

While this is currently not producing error in the binaries in Release mode, it needs to be corrected.

**Comment by olivier-stasse** [comment]
Could give the line ?

**Comment by proyan** [comment]
The line is this
https://github.com/stack-of-tasks/dynamic_graph_bridge/blob/master/src/sot_loader.cpp#L91

**Comment by olivier-stasse** [comment]
I think that now the assert in
rl-umi3218/jrl-cmakemodules/pull/360/commits/7a7b9ab8dacbca6d7ed850848ac977c3e33561c0
make sure that angleControl_ exists and has been initialized.
Fixed by commit 539e23ed4ae7e
Thanks for this @proyan
