### ISSUE TITLE
ros_joint_state

### ISSUE THREAD

**Issue by olivier-stasse** [stack-of-tasks/dynamic_graph_bridge#41]
This plugin should not be located in this package but rather in some sot-ros-utils.
It creates an unnecessary dependencies to pinocchio.
geometry_simu does the same thing just by using the robot device.

ros_joint_state will be remove unless it is found useful by others.

**Comment by jmirabel** [comment]
I don't mind it being moved in another package. However, I find it convenient to publish the joint states.

**Comment by olivier-stasse** [comment]
`/joint_states` on pyrene are not published through this entity but rather by roscontrol.
Do you really listen to the topic `dynamic_graph/joint_states` ?

**Comment by jmirabel** [comment]
No, I listen to `/joint_states`.

**Comment by olivier-stasse** [comment]
Therefore the modification should not impact your code.

**Comment by olivier-stasse** [comment]
Fixed by #44
