### ISSUE TITLE
Python file install in dist-packages

### ISSUE THREAD

**Issue by olivier-stasse** [stack-of-tasks/dynamic_graph_bridge#58]
Following commit 86cfdc71 python files are installed in dist-packages breaking the robotpkg building chain.

**Comment by nim65s** [comment]
Please add `-DPYTHON_STANDARD_LAYOUT=ON` to your CMake options, ref https://github.com/jrl-umi3218/jrl-cmakemodules/pull/234

**Comment by olivier-stasse** [comment]
Thanks for the answer. 
I just messed up my installation.
Robotpkg is taking care of this nicely.
I probably mixed it with local source install.
