### ISSUE TITLE
geometric_simu crashes

### ISSUE THREAD

**Issue by florent-lamiraux** [stack-of-tasks/dynamic_graph_bridge#63]
Running geometric_simu terminates with the following 
```
exception:terminate called after throwing an instance of 'std::runtime_error'
  what():  SingleThreadedSpinner: Attempt to spin a callback queue from two spinners, one of them being single-threaded. You might want to use a MultiThreadedSpinner instead.
Aborted (core dumped)
```
I am on devel branch, ubuntu-18.04 and ros-melodic.

**Comment by jmirabel** [comment]
Overall, the usage of ros spinners in SoT should be revised.

**Comment by olivier-stasse** [comment]
It is probably due to the fact that rosInit is called multiple times accross the repository and with different settings. This should indeed be investiguated and fixed.
